version: '3.8'
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.12.2
    hostname: ${COMBINED_HOSTNAME}
    command: "-e -system.hostfs=/hostfs"
    network_mode: host
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/hostfs/var/run/dbus/system_bus_socket
      - ES_HOSTS=${ES_HOSTS}
      - KIBANA_HOST=${KIBANA_HOST}
      - ES_API_KEY=${ES_API_KEY}
    volumes:
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
      - type: bind
        source: /var/run/dbus/system_bus_socket
        target: /hostfs/var/run/dbus/system_bus_socket
        read_only: true  

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    user: root
    volumes:
      - /var/log:/var/log
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ES_HOSTS=${ES_HOSTS}
      - KIBANA_HOST=${KIBANA_HOST}
      - ES_API_KEY=${ES_API_KEY}
