metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

metricbeat.modules:
- module: system
  metricsets:
    - "cpu"
    - "memory"
    - "diskio"
    - "memory"
    - "network"
    - "process"
    - "process_summary"
  period: 5s
  enabled: true

processors:
  - add_cloud_metadata: ~

logging.level: info
logging.to_files: false
logging.to_syslog: false
logging.to_stderr: true

output.elasticsearch:
  hosts: ["${ES_HOSTS}"]
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.kibana:
  host: "${KIBANA_HOST}"
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.dashboards.enabled: true