metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 5s

metricbeat.modules:
- module: system
  metricsets: ["cpu", "load", "filesystem", "fsstat", "memory", "network", "process", "core", "diskio", "socket"]
  period: 5s
  enabled: true
  processes: ['.*']

  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

logging.level: info
logging.to_files: false
logging.to_syslog: false
logging.to_stderr: true

output.elasticsearch:
  hosts: ["${ES_HOSTS}"]
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.kibana:
  host: "${KIBANA_HOST}"
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.dashboards.enabled: true