metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


metricbeat.modules:
- module: system
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  period: 5s
  enabled: true

- module: docker
  period: 10s
  metricsets:
    - container
    - cpu
    - diskio
    - memory
    - network
    - load
    - process
    - process_summary
  hosts: ["unix:///var/run/docker.sock"]

processors:
  - add_cloud_metadata: ~

logging.level: info
logging.to_files: false
logging.to_syslog: false
logging.to_stderr: true

output.elasticsearch:
  hosts: ["${ES_HOSTS}"]
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.kibana:
  host: "${KIBANA_HOST}"
  api_key: "${ES_API_KEY}"
  ssl.verification_mode: none

setup.dashboards.enabled: true